image: Visual Studio 2015

configuration:
  - debug
  - release

platform:
  - x86
  - x64

environment:
  global:
    STRESS: 1
  matrix:
    - { LUA: "lua 5.1",    LUA_NAME: "lua5.1" }
    - { LUA: "lua 5.2",    LUA_NAME: "lua5.2" }
    - { LUA: "lua 5.3",    LUA_NAME: "lua5.3" }
    - { LUA: "luajit 2.0", LUA_NAME: "luajit2.0" }
    # - LUA: "luajit 2.1" # currently failing

before_build:
  - git submodule update --init --recursive
  - pip install hererocks
  - if "%PLATFORM%"=="x86" (set WinType="32") else (set WinType="64")
  - hererocks env --%LUA% -rlatest --target vs_%WinType%
  - call env\bin\activate

build_script:
  - mkdir build
  - cd build
  - if "%PLATFORM%"=="x86" (set WinType="Win32") else (set WinType="x64")
  - cmake .. -G "Visual Studio 14 2015" -A %WinType%
  - cmake --build . --config %CONFIGURATION%
  - 7z a effil-%APPVEYOR_REPO_TAG_NAME%-%LUA_NAME%-Win-%PLATFORM%.zip effil.dll

test_script:
  - lua ../tests/lua/run_tests

artifacts:
  - path: build/*.zip

deploy:
    provider: GitHub
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
        secure: MmJswKplsV+hzQb/WtStw825jGE74AwQsBlqMRW7/2stpVPVwahjOcLuIv9WXkbL
    artifact: /.*\.zip/
    force_update: true
    on:
        appveyor_repo_tag: true
        configuration: release
